### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by belmix** [j-bitmaker/react-template-law#35]
PS C:\react-template-law> npm start

> law@0.1.0 start
> react-scripts start

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\react-template-law\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\react-template-law\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (C:\react-template-law\node_modules\webpack\lib\NormalModule.js:434:10)
    at C:\react-template-law\node_modules\webpack\lib\NormalModule.js:466:5
    at C:\react-template-law\node_modules\webpack\lib\NormalModule.js:327:12
    at C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\react-template-law\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\react-template-law\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
C:\react-template-law\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\react-template-law\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\react-template-law\node_modules\webpack\lib\NormalModule.js:386:16)
    at C:\react-template-law\node_modules\webpack\lib\NormalModule.js:418:10
    at C:\react-template-law\node_modules\webpack\lib\NormalModule.js:293:13
    at C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\react-template-law\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\react-template-law\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
PS C:\react-template-law>

**Comment by belmix** [comment]
change in package.json
`"start": "react-scripts start",`
`"start": "react-scripts --openssl-legacy-provider start",`

**Comment by belmix** [comment]
PS C:\react-template-law> npm start

> law@0.1.0 start
> react-scripts --openssl-legacy-provider start

Compiled with warnings.

./src/components/button-list/index.js
  Line 34:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 42:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 50:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 61:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 69:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 77:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 89:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 97:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text
  Line 105:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images
jsx-a11y/alt-text

./src/components/template-page-text/confident-text.js
  Line 61:  'legal_address_2' is assigned a value but never used  no-unused-vars
  Line 61:  'INN_2' is assigned a value but never used            no-unused-vars
  Line 61:  'KPP_2' is assigned a value but never used            no-unused-vars
  Line 61:  'ORGN_2' is assigned a value but never used           no-unused-vars
  Line 62:  'pay_account_2' is assigned a value but never used    no-unused-vars
  Line 62:  'cor_account_2' is assigned a value but never used    no-unused-vars
  Line 62:  'BIK_2' is assigned a value but never used            no-unused-vars

./src/components/template-page-text/order-po-text.js
  Line 7:  'city' is assigned a value but never used    no-unused-vars
  Line 7:  'day' is assigned a value but never used     no-unused-vars
  Line 7:  'month' is assigned a value but never used   no-unused-vars
  Line 7:  'year' is assigned a value but never used    no-unused-vars
  Line 9:   'name_1' is assigned a value but never used  no-unused-vars
  Line 16:  'name_2' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by belmix** [comment]
change in \src\components\helper-pdf\index.js

`import * as jsPDF from 'jspdf';`

`import { jsPDF } from "jspdf";`

**Comment by belmix** [comment]
Line 34:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 42:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 50:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 61:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 69:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 77:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 89:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 97:   img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line 105:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

change in \src\components\button-list\index.js

```
<img src={secure} width='200px' height='200px'/>
...
<img src={mark} width='200px' height='200px'/>
...
<img src={person} width='200px' height='200px'/>
...
<img src={handshake} width='200px' height='200px'/>
...
<img src={prog} width='200px' height='200px'/>
...
<img src={order} width='200px' height='200px'/>
...
<img src={list} width='200px' height='200px'/>
...
<img src={deal} width='200px' height='200px'/>
...
<img src={secure} width='200px' height='200px'/>
```

```
<img src={secure} alt='button' width='200px' height='200px'/>
...
<img src={mark} alt='button' width='200px' height='200px'/>
...
<img src={person} alt='button' width='200px' height='200px'/>
...
<img src={handshake} alt='button' width='200px' height='200px'/>
...
<img src={prog} alt='button' width='200px' height='200px'/>
...
<img src={order} alt='button' width='200px' height='200px'/>
...
<img src={list} alt='button' width='200px' height='200px'/>
...
<img src={deal} alt='button' width='200px' height='200px'/>
...
<img src={secure} alt='button' width='200px' height='200px'/>
```

**Comment by belmix** [comment]
index.js:1210 Warning: Invalid DOM property `class`. Did you mean `className`?
    in span (at navbar/index.js:17)

change in \src\components\navbar\index.js

` <Link to="/" className="nav-link">Главная<span class="sr-only">(current)</span></Link>`

`<Link to="/" className="nav-link">Главная<span className="sr-only">(current)</span></Link>`

**Comment by belmix** [comment]
webpackHotDevClient.js:115 ./src/components/template-page-text/order-po-text.js
  Line 7:  'city' is assigned a value but never used    no-unused-vars
  Line 7:  'day' is assigned a value but never used     no-unused-vars
  Line 7:  'month' is assigned a value but never used   no-unused-vars
  Line 7:  'year' is assigned a value but never used    no-unused-vars
  Line 9:   'name_1' is assigned a value but never used  no-unused-vars
  Line 16:  'name_2' is assigned a value but never used  no-unused-vars

change in \src\components\template-page-text\order-po-text.js

`г.____________ "__" ___________ 20__ г.`

`г. {city} "{day}" {month} {year} г.`


```
____________________ в лице __________________, действующего на основании
______________, именуемое в дальнейшем "Заказчик", с одной стороны и
______________________________ в лице _____________________________________
```

```
____________________ в лице {name_1}, действующего на основании
______________, именуемое в дальнейшем "Заказчик", с одной стороны и
______________________________ в лице {name_2}
```
